name: Check For Updates

on:
  schedule:
  - cron: "*/10 * * * *"    # Every 30 minutes

  workflow_dispatch:
  
jobs:
  tag:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates.
        id: check
        shell: bash
        run: |
          source <(echo "{ ${{ secrets.CFU }} }")
          exit 0
          curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/main.yml/runs|grep -q progress && exit 0 || (
          for a in $(curl -qs https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/check.yml/runs|grep -B 1 "Check For Updates"|grep id|tr -d " ,"|cut -d ":" -f 2);do curl -qs -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.WF }} " "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$a";done
          revision=$(svn info --show-item revision https://svn.code.sf.net/p/vice-emu/code/trunk/vice)
          curl -qs "https://github.com/$GITHUB_REPOSITORY/tags"|grep "class.*releases/tag/"|grep -q $revision && exit 0 || (
          curl -v -X POST -d '{"ref":"main"}' -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WF }} " \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/main.yml/dispatches" || exit 0 && \
          echo "New revision $revision on SVN!"
          sleep 60
          )
          )
